### ISSUE TITLE
Stress-testing

### ISSUE THREAD

**Issue by T-Maxxx** [callofduty4x/mysql#3]
Need help with testing this plugin. I'm have no experience with mysql database so any help required. Feel free to add issues and discuss features and solutions.

**Comment by MichaelHillcox** [comment]
@T-Maxxx I'll set something up today on a main server if all is going well. The server averages about 20 players so I will set something up to update a the mysql database every time the player gets xp. Don't think I can think of a more intensive test than that. Other than setting lots of servers up at a time but that would be testing my mysql servers more than the plugin.
