### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by d1st4r** [callofduty4x/mysql#4]
http://pastebin.com/raw/N5R9NEhp

**Comment by icekobrin** [comment]
There was not a single query to the database.

**Comment by d1st4r** [comment]
http://pastebin.com/raw/LhVqnY4j -> plugin_main.c
http://pastebin.com/raw/v5tBUd9i -> logfile
Bug?

**Comment by D4edalus** [comment]
probably. did you find out where its crashing exactly? from your log it looks like OnExitLevel might be the problem. ist this happening without a gsc script calling these functions? if you are using a gsc script you should provide one to recreate the error.

**Comment by T-Maxxx** [comment]
```C
Com_Printf("%s  ^1OnExitLevel\n", g_mysql_res[i]);
```
Не надо печатать указатели, тем более какого-то страшного, типа как строчку. Печатай как десятичное или шестнадцатиричное число, "%d", "0x%X".

**Comment by d1st4r** [comment]
> probably. did you find out where its crashing exactly? from your log it looks like OnExitLevel might be the problem. ist this happening without a gsc script calling these functions? if you are using a gsc script you should provide one to recreate the error.

this happens without GSC functions.

> Не надо печатать указатели, тем более какого-то страшного, типа как строчку. Печатай как десятичное или шестнадцатиричное число, "%d", "0x%X".

Хорошо.

**Comment by d1st4r** [comment]
http://pastebin.com/raw/qFVA5hxL -> plugin_main.c
http://pastebin.com/raw/cgNSNA7s -> logfile
https://github.com/callofduty4x/mysql/blob/master/plugin_main.c#L67
Incorrect use?

**Comment by T-Maxxx** [comment]
Всё нормально. Это просто инициализация. Ты должен вручную создать соединение, используя скриптовую функцию `mysql_real_connect`, а перед загрузкой следующей карты - закрыть соединение с помощью `mysql_close`.

**Comment by d1st4r** [comment]
Все равно мне не дает покоя, при использовании команды quit в консоли сервера. Краш есть...
А если админ решить карту поменять через map_rotate?

**Comment by d1st4r** [comment]
http://pastebin.com/raw/0d6bdG25 -> plugin_name.c
http://pastebin.com/raw/sD1rtidG -> logfile
wtf?

**Comment by volkv** [comment]
Да, надо закрывать все коннекты сразу после выполнения, иначе СегментейшенФак...

**Comment by T-Maxxx** [comment]
@icekobrin Переписал плагин на С++, нашёл краш - он, оказывается, был связан с выгрузкой библиотеки - совсем не очевидная вещь. Можешь проверить, твоя проблема решена?

**Comment by d1st4r** [comment]
https://pastebin.com/raw/JcK3d3w7

**Comment by T-Maxxx** [comment]
Плагин добавляет скриптовые функции, которые кидаются в общий список функций сервера. Кому-то было лень писать код на очиску этих функций, поэтому и выбрасывает ошибку о попытке выгрузить плагин. Это нормально.
