### ISSUE TITLE
MySQL store error on Update

### ISSUE THREAD

**Issue by volkv** [callofduty4x/mysql#6]
Hey guys! Idk what is wrong here...
Iam doing a simple update (upd: and insert also) cmds like
```
mysql = mysql_real_connect("localhost", "root", "1234", "cod4");			
mysql_query(mysql, "UPDATE stats SET kills = 1 WHERE guid = 2310346615860255566");
mysql_close(mysql);
```
And after each of UPDATE query I always receive this fatal error: **MySQL store error(0)**
https://github.com/callofduty4x/mysql/blob/6e10c80c73949fe1ff5953dc6e360fda51d1abbe/script_functions.c#L272

But even so I got my table row updated...

What I see in MySQL error.log is:
**2017-03-25 [Note] Aborted connection 221969 to db: 'cod4' user: 'root' host: 'localhost' (Got an error reading communication packets)**

P.S. its ok with my SELECT queries...
P.S.S. MySQL ver. : 5.7.17-0 ubuntu 16.10.1

**Comment by T-Maxxx** [comment]
https://github.com/callofduty4x/mysql/blob/6e10c80c73949fe1ff5953dc6e360fda51d1abbe/script_functions.c#L270
Please, check your post because you getting mysql_errno value 0 but this line says if-statements will be ignored when errno == 0 so you can not get this error.

**Comment by volkv** [comment]
No, iam sure its exactly **MySQL store error: (0)**
are you sure mysql_errno(&g_mysql[handle]) == 0 would be equal **false**?
look
![error](http://cod4narod.ru/mysql.png)

**Comment by T-Maxxx** [comment]
`if(g_mysql_res[handle] == NULL && mysql_errno(&g_mysql[handle]))`
`If (I'm failed to save query result && mysql_errno not equal 0)`
BUT. "MySQL store error: (0)" means mysql_errno == 0. And mysql_errno can't be equal 0 because of "if" condition. WTF?
The only reason I see is mysql_errno call changes internal mysql errno value. LOL.
Please, correct if I'm wrong.

**Comment by volkv** [comment]
я сегодня прихерел от того, как сложно добраться из скриптов до статистики о.О
начиная от того, что всякие XLTstats не работают с PHP7.0, B3 неадекват и закончиваю щас тем, что мигрирую ReCoD с SQLITE на MYSQL

**Comment by T-Maxxx** [comment]
@volkv Исправлено?
